
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const App = lazy(() => import("./pages/App.tsx"));
const Help = lazy(() => import("./pages/Help.tsx"));
const History = lazy(() => import("./pages/History.tsx"));
const Landing = lazy(() => import("./pages/Landing.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <UserGuard><App /></UserGuard>},
	{ path: "/help", element: <UserGuard><Help /></UserGuard>},
	{ path: "/history", element: <UserGuard><History /></UserGuard>},
	{ path: "/landing", element: <Landing />},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},

];
